In [1]:
import pandas as pd
import quandl

In [5]:
BRA_df = quandl.get("UNAE/GVAKD_BRA",authtoken="***********")

In [8]:
BRA_df.head()

,Agriculture; hunting; forestry; fishing (ISIC A-B),Mining; Manufacturing; Utilities (ISIC C-E),Manufacturing (ISIC D),Construction (ISIC F),Wholesale; retail trade; restaurants and hotels (ISIC G-H),Transport; storage and communication (ISIC I),Other Activities (ISIC J-P),Total Value Added
Date,,,,,,,,
1970-12-31,2.157553e+10,9.730459e+10,7.275022e+10,2.684677e+10,4.672263e+10,2.399507e+10,1.512378e+11,3.639299e+11
1971-12-31,2.377624e+10,1.087866e+11,8.133496e+10,3.001461e+10,5.195554e+10,2.668248e+10,1.681765e+11,4.051567e+11
1972-12-31,2.472729e+10,1.242340e+11,9.288418e+10,3.427700e+10,5.839793e+10,2.999095e+10,1.890306e+11,4.557835e+11
1973-12-31,2.475202e+10,1.453533e+11,1.086738e+11,4.010450e+10,6.750798e+10,3.466948e+10,2.185194e+11,5.253258e+11
1974-12-31,2.507379e+10,1.577085e+11,1.179112e+11,4.351330e+10,7.466413e+10,3.834501e+10,2.416817e+11,5.753985e+11

In [6]:
BRA_df.describe()

,Agriculture; hunting; forestry; fishing (ISIC A-B),Mining; Manufacturing; Utilities (ISIC C-E),Manufacturing (ISIC D),Construction (ISIC F),Wholesale; retail trade; restaurants and hotels (ISIC G-H),Transport; storage and communication (ISIC I),Other Activities (ISIC J-P),Total Value Added
count,4.800000e+01,4.800000e+01,4.800000e+01,4.800000e+01,4.800000e+01,4.800000e+01,4.800000e+01,4.800000e+01
mean,5.696842e+10,2.729176e+11,1.986851e+11,7.760964e+10,1.700785e+11,9.304921e+10,5.422238e+11,1.210501e+12
std,2.608904e+10,8.305836e+10,5.632510e+10,2.777746e+10,7.319906e+10,4.448698e+10,2.237973e+11,4.776210e+11
min,2.157553e+10,9.730459e+10,7.275022e+10,2.684677e+10,4.672263e+10,2.399507e+10,1.512378e+11,3.639299e+11
25%,3.683686e+10,2.156053e+11,1.612074e+11,5.949329e+10,1.140187e+11,5.855187e+10,3.690906e+11,8.463804e+11
50%,4.880553e+10,2.678109e+11,2.008700e+11,7.342608e+10,1.626379e+11,8.322090e+10,5.236993e+11,1.151361e+12
75%,7.834912e+10,3.413244e+11,2.411096e+11,8.527952e+10,2.172207e+11,1.239902e+11,7.020252e+11,1.553894e+12
max,1.071098e+11,4.083525e+11,2.889374e+11,1.372850e+11,3.032845e+11,1.773869e+11,9.229713e+11,2.040560e+12

In [7]:
RUS_df = quandl.get("UNAE/GVAKD_RUS",authtoken="**********")

In [9]:
RUS_df.head()

,Agriculture; hunting; forestry; fishing (ISIC A-B),Mining; Manufacturing; Utilities (ISIC C-E),Manufacturing (ISIC D),Construction (ISIC F),Wholesale; retail trade; restaurants and hotels (ISIC G-H),Transport; storage and communication (ISIC I),Other Activities (ISIC J-P),Total Value Added
Date,,,,,,,,
1990-12-31,6.644247e+10,4.726896e+11,2.444101e+11,1.202085e+11,1.388710e+11,1.383119e+11,3.020482e+11,1.226269e+12
1991-12-31,6.398072e+10,4.457487e+11,2.304832e+11,1.057874e+11,1.341787e+11,1.303391e+11,3.048563e+11,1.175323e+12
1992-12-31,5.822287e+10,3.659156e+11,1.892012e+11,7.087659e+10,1.277053e+11,1.093772e+11,2.872629e+11,1.012969e+12
1993-12-31,5.589396e+10,3.131072e+11,1.618938e+11,6.520645e+10,1.237465e+11,8.734320e+10,2.924582e+11,9.401008e+11
1994-12-31,4.929516e+10,2.503759e+11,1.294673e+11,5.281723e+10,1.236227e+11,7.327257e+10,2.629838e+11,8.156882e+11

In [40]:
# test_df = quandl.get(["UNAE/GVACD_BRA", "UNAE/GVAKD_RUS"],authtoken="Pjy4pjUdbZ7yRYkxkzj4")
# test_df = quandl.get("UNAE/GVACD_BRA")

In [10]:
# test_df.head()

In [ ]:
authtoken="************"

In [42]:
#*******************************************************

In [11]:
tickers = pd.read_csv('ticker_list.csv')
tickers.head()

      Country  Code         Q_Ticker
0       World  5001  UNAE/GVAKD_5001
1     Belgium   BEL   UNAE/GVAKD_BEL
2  Czech Rep.   CZE   UNAE/GVAKD_CZE
3      France   FRA   UNAE/GVAKD_FRA
4     Germany   DEU   UNAE/GVAKD_DEU

In [12]:
tickers.Country[16]

'Russia'

In [13]:
RUS_df.head()

,Agriculture; hunting; forestry; fishing (ISIC A-B),Mining; Manufacturing; Utilities (ISIC C-E),Manufacturing (ISIC D),Construction (ISIC F),Wholesale; retail trade; restaurants and hotels (ISIC G-H),Transport; storage and communication (ISIC I),Other Activities (ISIC J-P),Total Value Added
Date,,,,,,,,
1990-12-31,6.644247e+10,4.726896e+11,2.444101e+11,1.202085e+11,1.388710e+11,1.383119e+11,3.020482e+11,1.226269e+12
1991-12-31,6.398072e+10,4.457487e+11,2.304832e+11,1.057874e+11,1.341787e+11,1.303391e+11,3.048563e+11,1.175323e+12
1992-12-31,5.822287e+10,3.659156e+11,1.892012e+11,7.087659e+10,1.277053e+11,1.093772e+11,2.872629e+11,1.012969e+12
1993-12-31,5.589396e+10,3.131072e+11,1.618938e+11,6.520645e+10,1.237465e+11,8.734320e+10,2.924582e+11,9.401008e+11
1994-12-31,4.929516e+10,2.503759e+11,1.294673e+11,5.281723e+10,1.236227e+11,7.327257e+10,2.629838e+11,8.156882e+11

In [14]:
a=RUS_df.reset_index()
a.head()

,Date,Agriculture; hunting; forestry; fishing (ISIC A-B),Mining; Manufacturing; Utilities (ISIC C-E),Manufacturing (ISIC D),Construction (ISIC F),Wholesale; retail trade; restaurants and hotels (ISIC G-H),Transport; storage and communication (ISIC I),Other Activities (ISIC J-P),Total Value Added
0,1990-12-31,6.644247e+10,4.726896e+11,2.444101e+11,1.202085e+11,1.388710e+11,1.383119e+11,3.020482e+11,1.226269e+12
1,1991-12-31,6.398072e+10,4.457487e+11,2.304832e+11,1.057874e+11,1.341787e+11,1.303391e+11,3.048563e+11,1.175323e+12
2,1992-12-31,5.822287e+10,3.659156e+11,1.892012e+11,7.087659e+10,1.277053e+11,1.093772e+11,2.872629e+11,1.012969e+12
3,1993-12-31,5.589396e+10,3.131072e+11,1.618938e+11,6.520645e+10,1.237465e+11,8.734320e+10,2.924582e+11,9.401008e+11
4,1994-12-31,4.929516e+10,2.503759e+11,1.294673e+11,5.281723e+10,1.236227e+11,7.327257e+10,2.629838e+11,8.156882e+11

In [15]:
# Date column only keeps year
a['Date'] = pd.DatetimeIndex(a['Date']).year

In [16]:
a.head()

,Date,Agriculture; hunting; forestry; fishing (ISIC A-B),Mining; Manufacturing; Utilities (ISIC C-E),Manufacturing (ISIC D),Construction (ISIC F),Wholesale; retail trade; restaurants and hotels (ISIC G-H),Transport; storage and communication (ISIC I),Other Activities (ISIC J-P),Total Value Added
0,1990,6.644247e+10,4.726896e+11,2.444101e+11,1.202085e+11,1.388710e+11,1.383119e+11,3.020482e+11,1.226269e+12
1,1991,6.398072e+10,4.457487e+11,2.304832e+11,1.057874e+11,1.341787e+11,1.303391e+11,3.048563e+11,1.175323e+12
2,1992,5.822287e+10,3.659156e+11,1.892012e+11,7.087659e+10,1.277053e+11,1.093772e+11,2.872629e+11,1.012969e+12
3,1993,5.589396e+10,3.131072e+11,1.618938e+11,6.520645e+10,1.237465e+11,8.734320e+10,2.924582e+11,9.401008e+11
4,1994,4.929516e+10,2.503759e+11,1.294673e+11,5.281723e+10,1.236227e+11,7.327257e+10,2.629838e+11,8.156882e+11

In [17]:
#Reaname columns
a.columns =["Year","Agriculture","Mining","Manufacturing","Construction","Wholesale","Transport","Other","Total"]
a.head()

,Year,Agriculture,Mining,Manufacturing,Construction,Wholesale,Transport,Other,Total
0,1990,6.644247e+10,4.726896e+11,2.444101e+11,1.202085e+11,1.388710e+11,1.383119e+11,3.020482e+11,1.226269e+12
1,1991,6.398072e+10,4.457487e+11,2.304832e+11,1.057874e+11,1.341787e+11,1.303391e+11,3.048563e+11,1.175323e+12
2,1992,5.822287e+10,3.659156e+11,1.892012e+11,7.087659e+10,1.277053e+11,1.093772e+11,2.872629e+11,1.012969e+12
3,1993,5.589396e+10,3.131072e+11,1.618938e+11,6.520645e+10,1.237465e+11,8.734320e+10,2.924582e+11,9.401008e+11
4,1994,4.929516e+10,2.503759e+11,1.294673e+11,5.281723e+10,1.236227e+11,7.327257e+10,2.629838e+11,8.156882e+11

In [18]:
# Add Country column
a['Country'] = tickers.Country[16]
a.head()

,Year,Agriculture,Mining,Manufacturing,Construction,Wholesale,Transport,Other,Total,Country
0,1990,6.644247e+10,4.726896e+11,2.444101e+11,1.202085e+11,1.388710e+11,1.383119e+11,3.020482e+11,1.226269e+12,Russia
1,1991,6.398072e+10,4.457487e+11,2.304832e+11,1.057874e+11,1.341787e+11,1.303391e+11,3.048563e+11,1.175323e+12,Russia
2,1992,5.822287e+10,3.659156e+11,1.892012e+11,7.087659e+10,1.277053e+11,1.093772e+11,2.872629e+11,1.012969e+12,Russia
3,1993,5.589396e+10,3.131072e+11,1.618938e+11,6.520645e+10,1.237465e+11,8.734320e+10,2.924582e+11,9.401008e+11,Russia
4,1994,4.929516e+10,2.503759e+11,1.294673e+11,5.281723e+10,1.236227e+11,7.327257e+10,2.629838e+11,8.156882e+11,Russia

In [20]:
#Create new df with desired column order
aa = a[ ['Country'] + [ col for col in a.columns if col != 'Country' ] ]
aa.head()

,Country,Year,Agriculture,Mining,Manufacturing,Construction,Wholesale,Transport,Other,Total
0,Russia,1990,6.644247e+10,4.726896e+11,2.444101e+11,1.202085e+11,1.388710e+11,1.383119e+11,3.020482e+11,1.226269e+12
1,Russia,1991,6.398072e+10,4.457487e+11,2.304832e+11,1.057874e+11,1.341787e+11,1.303391e+11,3.048563e+11,1.175323e+12
2,Russia,1992,5.822287e+10,3.659156e+11,1.892012e+11,7.087659e+10,1.277053e+11,1.093772e+11,2.872629e+11,1.012969e+12
3,Russia,1993,5.589396e+10,3.131072e+11,1.618938e+11,6.520645e+10,1.237465e+11,8.734320e+10,2.924582e+11,9.401008e+11
4,Russia,1994,4.929516e+10,2.503759e+11,1.294673e+11,5.281723e+10,1.236227e+11,7.327257e+10,2.629838e+11,8.156882e+11

In [21]:
# Calculate Total column
aa['Total'] = aa.loc[:,'Agriculture':'Other'].sum(axis=1)

In [22]:
aa.head()

,Country,Year,Agriculture,Mining,Manufacturing,Construction,Wholesale,Transport,Other,Total
0,Russia,1990,6.644247e+10,4.726896e+11,2.444101e+11,1.202085e+11,1.388710e+11,1.383119e+11,3.020482e+11,1.482982e+12
1,Russia,1991,6.398072e+10,4.457487e+11,2.304832e+11,1.057874e+11,1.341787e+11,1.303391e+11,3.048563e+11,1.415374e+12
2,Russia,1992,5.822287e+10,3.659156e+11,1.892012e+11,7.087659e+10,1.277053e+11,1.093772e+11,2.872629e+11,1.208562e+12
3,Russia,1993,5.589396e+10,3.131072e+11,1.618938e+11,6.520645e+10,1.237465e+11,8.734320e+10,2.924582e+11,1.099649e+12
4,Russia,1994,4.929516e+10,2.503759e+11,1.294673e+11,5.281723e+10,1.236227e+11,7.327257e+10,2.629838e+11,9.418346e+11

In [34]:
aaa=aa.loc[:,"Agriculture":"Total"].div(aa["Total"], axis=0)*100
aaa.head()

,Agriculture,Mining,Manufacturing,Construction,Wholesale,Transport,Other,Total
0,4.480329,31.874269,16.480990,8.105865,9.364308,9.326609,20.367630,100.0
1,4.520410,31.493347,16.284259,7.474167,9.480088,9.208810,21.538918,100.0
2,4.817534,30.276950,15.655071,5.864541,10.566718,9.050199,23.768988,100.0
3,5.082890,28.473370,14.722310,5.929750,11.253266,7.942824,26.595590,100.0
4,5.233951,26.583846,13.746285,5.607909,13.125734,7.779771,27.922504,100.0

In [58]:
final = pd.DataFrame([aa['Country'],aa['Year'],aaa["Agriculture"],aaa["Mining"],aaa["Manufacturing"],aaa["Construction"],aaa["Wholesale"],aaa["Transport"],aaa["Other"]])

In [59]:
final.transpose().head()

,Country,Year,Agriculture,Mining,Manufacturing,Construction,Wholesale,Transport,Other
0,Russia,1990,4.48033,31.8743,16.481,8.10587,9.36431,9.32661,20.3676
1,Russia,1991,4.52041,31.4933,16.2843,7.47417,9.48009,9.20881,21.5389
2,Russia,1992,4.81753,30.2769,15.6551,5.86454,10.5667,9.0502,23.769
3,Russia,1993,5.08289,28.4734,14.7223,5.92975,11.2533,7.94282,26.5956
4,Russia,1994,5.23395,26.5838,13.7463,5.60791,13.1257,7.77977,27.9225

In [62]:
r=pd.concat([BRA_df,RUS_df], axis=0)

In [63]:
r

,Agriculture; hunting; forestry; fishing (ISIC A-B),Mining; Manufacturing; Utilities (ISIC C-E),Manufacturing (ISIC D),Construction (ISIC F),Wholesale; retail trade; restaurants and hotels (ISIC G-H),Transport; storage and communication (ISIC I),Other Activities (ISIC J-P),Total Value Added
Date,,,,,,,,
1970-12-31,2.157553e+10,9.730459e+10,7.275022e+10,2.684677e+10,4.672263e+10,2.399507e+10,1.512378e+11,3.639299e+11
1971-12-31,2.377624e+10,1.087866e+11,8.133496e+10,3.001461e+10,5.195554e+10,2.668248e+10,1.681765e+11,4.051567e+11
1972-12-31,2.472729e+10,1.242340e+11,9.288418e+10,3.427700e+10,5.839793e+10,2.999095e+10,1.890306e+11,4.557835e+11
1973-12-31,2.475202e+10,1.453533e+11,1.086738e+11,4.010450e+10,6.750798e+10,3.466948e+10,2.185194e+11,5.253258e+11
1974-12-31,2.507379e+10,1.577085e+11,1.179112e+11,4.351330e+10,7.466413e+10,3.834501e+10,2.416817e+11,5.753985e+11
1975-12-31,2.672866e+10,1.654386e+11,1.236912e+11,4.564314e+10,7.839750e+10,4.026244e+10,2.537655e+11,6.043595e+11
1976-12-31,2.737015e+10,1.847939e+11,1.381635e+11,5.098437e+10,8.749106e+10,4.493200e+10,2.832036e+11,6.723798e+11
1977-12-31,3.068194e+10,1.905186e+11,1.424415e+11,5.256858e+10,9.186488e+10,4.717746e+10,2.973655e+11,7.037896e+11
1978-12-31,2.985353e+10,2.027110e+11,1.515552e+11,5.593375e+10,9.756112e+10,5.010323e+10,3.158009e+11,7.453339e+11
1979-12-31,3.125664e+10,2.164993e+11,1.618661e+11,5.973350e+10,1.051736e+11,5.401659e+10,3.404260e+11,8.003010e+11
1980-12-31,3.423227e+10,2.365455e+11,1.768587e+11,6.523969e+10,1.146594e+11,5.888608e+10,3.711357e+11,8.732009e+11
1981-12-31,3.696059e+10,2.156120e+11,1.612119e+11,5.949439e+10,1.118105e+11,5.741767e+10,3.619439e+11,8.376886e+11
1982-12-31,3.687927e+10,2.155054e+11,1.611112e+11,5.948998e+10,1.141678e+11,5.862646e+10,3.695852e+11,8.492776e+11
1983-12-31,3.670963e+10,2.027632e+11,1.515839e+11,5.595318e+10,1.135715e+11,5.832812e+10,3.676068e+11,8.315444e+11
1984-12-31,3.767509e+10,2.155853e+11,1.611939e+11,5.945731e+10,1.196625e+11,6.148020e+10,3.872317e+11,8.773298e+11
1985-12-31,4.128436e+10,2.335117e+11,1.746153e+11,6.428117e+10,1.279448e+11,6.569582e+10,4.141718e+11,9.424078e+11
1986-12-31,3.797336e+10,2.604627e+11,1.947749e+11,7.204069e+10,1.382732e+11,7.097451e+10,4.477922e+11,1.022069e+12
1987-12-31,4.365797e+10,2.630326e+11,1.965132e+11,7.276225e+10,1.426356e+11,7.323394e+10,4.618054e+11,1.051923e+12
1988-12-31,4.402470e+10,2.564332e+11,1.916998e+11,7.064149e+10,1.460388e+11,7.505320e+10,4.723874e+11,1.061026e+12
1989-12-31,4.527940e+10,2.638688e+11,1.974438e+11,7.256468e+10,1.512628e+11,7.786668e+10,4.889216e+11,1.096316e+12
1990-12-31,4.359501e+10,2.427357e+11,1.816052e+11,6.619736e+10,1.498635e+11,7.671775e+10,4.859349e+11,1.064420e+12
1991-12-31,4.419226e+10,2.413144e+11,1.804842e+11,6.833173e+10,1.527002e+11,7.824377e+10,4.955446e+11,1.080348e+12
1992-12-31,4.659512e+10,2.324908e+11,1.728846e+11,6.436116e+10,1.541972e+11,7.927920e+10,4.986198e+11,1.076906e+12
1993-12-31,4.705484e+10,2.519571e+11,1.889253e+11,6.796634e+10,1.594772e+11,8.235099e+10,5.134810e+11,1.122193e+12
1994-12-31,5.055622e+10,2.717531e+11,2.042962e+11,7.408991e+10,1.657986e+11,8.605358e+10,5.339175e+11,1.180530e+12
1995-12-31,5.345622e+10,2.867384e+11,2.143773e+11,7.495186e+10,1.690357e+11,8.409080e+10,5.568517e+11,1.223372e+12
1996-12-31,5.503488e+10,2.884792e+11,2.145511e+11,7.737731e+10,1.725915e+11,8.885502e+10,5.624310e+11,1.242693e+12
1997-12-31,5.548233e+10,2.973928e+11,2.199008e+11,8.395712e+10,1.801182e+11,9.415376e+10,5.721586e+11,1.280399e+12
1998-12-31,5.737366e+10,2.871906e+11,2.092551e+11,8.489934e+10,1.822042e+11,9.609625e+10,5.742096e+11,1.280186e+12
1999-12-31,6.111742e+10,2.820923e+11,2.053575e+11,8.240150e+10,1.811332e+11,9.641517e+10,5.837532e+11,1.286037e+12
...,...,...,...,...,...,...,...,...
2016-12-31,1.000738e+11,3.516546e+11,2.388504e+11,1.242627e+11,2.831079e+11,1.668311e+11,8.798697e+11,1.911001e+12
2017-12-31,9.991900e+10,3.352027e+11,2.242005e+11,1.203286e+11,2.776363e+11,1.651738e+11,8.680650e+11,1.872652e+12
1990-12-31,6.644247e+10,4.726896e+11,2.444101e+11,1.202085e+11,1.388710e+11,1.383119e+11,3.020482e+11,1.226269e+12
1991-12-31,6.398072e+10,4.457487e+11,2.304832e+11,1.057874e+11,1.341787e+11,1.303391e+11,3.048563e+11,1.175323e+12
1992-12-31,5.822287e+10,3.659156e+11,1.892012e+11,7.087659e+10,1.277053e+11,1.093772e+11,2.872629e+11,1.012969e+12
1993-12-31,5.589396e+10,3.131072e+11,1.618938e+11,6.520645e+10,1.237465e+11,8.734320e+10,2.924582e+11,9.401008e+11
1994-12-31,4.929516e+10,2.503759e+11,1.294673e+11,5.281723e+10,1.236227e+11,7.327257e+10,2.629838e+11,8.156882e+11
1995-12-31,4.451481e+10,2.415154e+11,1.248731e+11,4.806368e+10,1.185542e+11,7.141349e+10,2.571922e+11,7.848489e+11
1996-12-31,4.221596e+10,2.349442e+11,1.214743e+11,3.999384e+10,1.209789e+11,6.808206e+10,2.589811e+11,7.689543e+11
1997-12-31,4.293670e+10,2.391952e+11,1.237119e+11,3.781881e+10,1.274470e+11,6.684822e+10,2.620489e+11,7.793477e+11
1998-12-31,3.508681e+10,2.272560e+11,1.174652e+11,3.543787e+10,1.193023e+11,6.491882e+10,2.618754e+11,7.493652e+11
1999-12-31,4.080381e+10,2.497669e+11,1.291342e+11,3.754678e+10,1.170082e+11,7.110781e+10,2.697540e+11,7.901709e+11
2000-12-31,4.572015e+10,2.777159e+11,1.437728e+11,4.407615e+10,1.312658e+11,7.548540e+10,2.763209e+11,8.518229e+11
2001-12-31,5.077637e+10,2.910778e+11,1.501781e+11,4.843969e+10,1.364309e+11,7.969783e+10,2.822341e+11,8.887976e+11
2002-12-31,5.225029e+10,3.021917e+11,1.563604e+11,4.979599e+10,1.476149e+11,8.424560e+10,2.902752e+11,9.250442e+11
2003-12-31,5.145965e+10,3.273198e+11,1.701191e+11,5.609798e+10,1.665716e+11,9.035199e+10,3.000964e+11,9.879512e+11
2004-12-31,5.205478e+10,3.599630e+11,1.838184e+11,6.164814e+10,1.832679e+11,9.568837e+10,3.065242e+11,1.051571e+12
2005-12-31,5.179998e+10,3.702035e+11,1.919749e+11,6.794448e+10,2.000345e+11,1.013521e+11,3.246921e+11,1.108806e+12
2006-12-31,5.324875e+10,3.803975e+11,2.045916e+11,7.662186e+10,2.277145e+11,1.112075e+11,3.506013e+11,1.192521e+12
2007-12-31,5.388465e+10,3.902868e+11,2.199818e+11,8.658890e+10,2.545741e+11,1.165947e+11,3.965384e+11,1.295802e+12
2008-12-31,5.700618e+10,3.874825e+11,2.153132e+11,9.617754e+10,2.797060e+11,1.227059e+11,4.243870e+11,1.367082e+12
2009-12-31,5.794566e+10,3.521384e+11,1.838432e+11,8.203751e+10,2.621433e+11,1.121830e+11,4.125789e+11,1.281214e+12
2010-12-31,5.100430e+10,3.776882e+11,1.996695e+11,8.567391e+10,2.774396e+11,1.183297e+11,4.222784e+11,1.332414e+12
2011-12-31,5.818063e+10,3.942821e+11,2.122134e+11,9.222235e+10,2.867335e+11,1.259833e+11,4.258200e+11,1.380533e+12
2012-12-31,5.748496e+10,4.065289e+11,2.219025e+11,9.575771e+10,2.967878e+11,1.310177e+11,4.455167e+11,1.431411e+12
2013-12-31,6.008743e+10,4.069919e+11,2.234836e+11,9.427920e+10,2.970145e+11,1.307772e+11,4.668876e+11,1.457725e+12
2014-12-31,6.099803e+10,4.081787e+11,2.251597e+11,9.404278e+10,3.068939e+11,1.351486e+11,4.661199e+11,1.470842e+12
2015-12-31,6.275481e+10,3.964582e+11,2.147402e+11,9.350077e+10,2.978551e+11,1.312694e+11,4.558040e+11,1.437741e+12
2016-12-31,6.484310e+10,3.970443e+11,2.172070e+11,9.243514e+10,2.951248e+11,1.299926e+11,4.545372e+11,1.434046e+12
2017-12-31,6.561605e+10,3.989207e+11,2.174025e+11,9.328246e+10,3.025643e+11,1.332854e+11,4.628410e+11,1.456531e+12